# Example configuration for SAREF use case

knowledgeBaseId = "http://example.org/ai"
knowledgeBaseName = "GLADoSS"
knowledgeBaseDescription = "Graph-based Live Anomaly Detection on Semantic Streams"

[[knowledgeInteraction]]
knowledgeInteractionEndpoint = "http://127.0.0.1:8000"
knowledgeInteractionName = "Device Observations Request"
argumentGraphPattern = """
  ?obs rdf:type saref:Observation .
  ?obs saref:madeBy ?device . 
  ?obs saref:hasTimestamp ?timestamp . 
  ?obs saref:hasResult ?result .
  ?result rdf:type saref:PropertyValue .
  ?result saref:isValueOfProperty ?prop .
  ?result saref:hasValue ?value .
  ?result saref:isMeasuredIn ?unit .
  """
[knowledgeInteraction.prefixes]
rdf = "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
saref = "https://saref.etsi.org/core/" 
