services:
  gladoss:
    build:
      context: .
      dockerfile: ../docker/Dockerfile 
    container_name: gladoss-ke
    image: gladoss-ke:latest
    volumes:
      - source: ./backup/
        target: /mnt/backup
        type: bind
        bind:
          create_host_path: true
      - source: ./logs/
        target: /var/log/gladoss
        type: bind
        bind:
          create_host_path: true
      - source: ./adaptors/
        target: /etc/gladoss/adaptors
        type: bind
        bind:
          create_host_path: true
    networks:
      - semantic_network

networks:
  semantic_network:
    name: semantic_network
    driver: bridge
    external: true
