# Example configuration for SAREF use case

knowledgeBaseId = "http://example.org/ai"
knowledgeBaseName = "GLADoSS"
knowledgeBaseDescription = "Graph-based Live Anomaly Detection on Semantic Streams"

[[knowledgeInteraction]]
knowledgeInteractionName = "Device Observations Request"
knowledgeInteractionType = "AskKnowledgeInteraction"
knowledgeInteractionPattern = """
  ?obs rdf:type saref:Observation .
  ?obs saref:madeBy ?device . 
  ?obs saref:hasTimestamp ?timestamp . 
  ?obs saref:hasResult ?result .
  ?result rdf:type saref:PropertyValue .
  ?result saref:isValueOfProperty ?prop .
  ?result saref:hasValue ?value .
  ?result saref:isMeasuredIn ?unit .
  """
knowledgeInteractionAnchors = [ # unique and stable nodes which can be used to match graphs to their patterns
  "?device",
  "?prop"
  ]
[knowledgeInteraction.prefixes]
rdf = "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
saref = "https://saref.etsi.org/core/" 
