# Example configuration for SAREF use case

knowledgeBaseId = "http://example.org/gladoss"
knowledgeBaseName = "GLADoSS"
knowledgeBaseDescription = "Graph-based Live Anomaly Detection on Semantic Streams"

[[knowledgeInteraction]]
knowledgeInteractionEndpoint = "http://127.0.0.1:8280/rest"
knowledgeInteractionName = "DeviceObservationsRequest"
argumentGraphPattern = """
  ?sensor rdf:type saref:Sensor .
  ?measurement saref:measurementMadeBy ?sensor .
  ?measurement saref:isMeasuredIn saref:TemperatureUnit .
  ?measurement saref:hasValue ?temperature .
  ?measurement saref:hasTimestamp ?timestamp .
  """
[knowledgeInteraction.prefixes]
rdf = "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
saref = "https://saref.etsi.org/core/" 
