# Configuration for dummy data generation
#
# type: IRIREF | string | float | int | dateTime
# changes_every: [1, inf]

[[data]]
namespace = "http://example.org/demo/"
pattern = """
  ?obs rdf:type saref:Observation .
  ?obs saref:madeBy ?device . 
  ?obs saref:hasTimestamp ?timestamp . 
  ?obs saref:hasResult ?result .
  ?result rdf:type saref:PropertyValue .
  ?result saref:isValueOfProperty ?prop .
  ?result saref:hasValue ?value .
  ?result saref:isMeasuredIn ?unit .
  """

[data.prefixes]
rdf = "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
saref = "https://saref.etsi.org/core/"

[[data.dynamic]]
name = "obs"
type = "IRIRef"
changes_every = 1

[[data.dynamic]]
name = "result"
type = "IRIRef"
changes_every = 1

[[data.dynamic]]
name = "timestamp"
type = "dateTime"
changes_every = 1
from = "2025-01-01T12:00:00"
to = "2025-02-01T12:00:00"

[[data.dynamic]]
name = "value"
type = "float"
changes_every = 1
from = -10.0
to = 40.0

[[data.static]]
name = "device"
type = "IRIRef"

[[data.static]]
name = "prop"
type = "IRIRef"
value = "Energy"

[[data.static]]
name = "unit"
type = "string"
value = "kWh"

# [[data]]  # add one or more graph generation configurations
