services:
  gladoss:
    build: .
    container_name: gladoss
    image: gladoss:latest
    volumes:
      - source: ./backup/
        target: /mnt/backup
        type: bind
        bind:
          create_host_path: true
      - source: ./adaptors/
        target: /etc/gladoss/adaptors
        type: bind
        bind:
          create_host_path: true
    networks:
      - semantic_network
    expose:
      - 8000
  gladoss-demo:
    build: .
    container_name: gladoss-demo
    image: gladoss:latest
    networks:
      - semantic_network
    expose:
      - 8000
    entrypoint: ''
    command: gladoss-demo --verbose --cachesize=5 --host "0.0.0.0" --port 8000

networks:
  semantic_network:
    name: semantic_network
    driver: bridge
    external: true
