services:
  gladoss:
    build: .
    container_name: gladoss
    image: gladoss:latest
    user: "${UID}:${GID}"
    volumes:
      - source: ./backup/
        target: /mnt/backup
        type: bind
        bind:
          create_host_path: true
      - source: ./logs/
        target: /var/log/gladoss
        type: bind
        bind:
          create_host_path: true
    ports:
      - "8000:8000"
  gladoss-demo:
    build: .
    container_name: gladoss-demo
    image: gladoss:latest
    user: "${UID}:${GID}"
    volumes:
      - source: ./logs/
        target: /var/log/gladoss
        type: bind
        bind:
          create_host_path: true
    ports:
      - "8000:8000"
    entrypoint: ''
    command: gladoss-demo --verbose --cachesize=5 --host "0.0.0.0" --port 8000
