services:
  gladoss:
    container_name: gladoss-rest
    image: gladoss-rest:latest
    volumes:
      - source: ../backup/
        target: /mnt/backup
        type: bind
        bind:
          create_host_path: true
      - source: ../adaptor/
        target: /etc/gladoss/adaptors
        type: bind
        bind:
          create_host_path: true
    networks:
      - semnet
    depends_on:
      gstreamsim
  gstreamsim:
    container_name: gstreamsim
    image: gstreamsim:latest
    ports:
      - 8000:8000
    networks:
      - semnet

networks:
  semnet:
    name: semnet
    driver: bridge
    external: true
